export const STOP_WORDS = new Set([
  "vs",
  "versus",
  "the",
  "a",
  "an",
  "and",
  "or",
  "for",
  "to",
  "of",
  "in",
  "on",
  "with",
  "how",
  "do",
  "does",
  "what",
  "which",
  "best",
  "some",
  "any",
  "from",
  "into",
  "about",
  "that",
  "this",
  "your",
  "our",
  "their",
  "have",
  "has",
  "been",
  "using",
  "use",
  "used",
  "make",
  "made",
  "need",
  "want",
  "looking",
  "help",
  "would",
  "could",
  "should",
  "like",
  "just",
  "also",
  "very",
  "more",
  "than",
  "then",
  "good",
  "great",
  "team",
  "teams",
  "frc",
  "robot",
  "robots",
  "other",
  "they",
  "them",
  "doing",
  "are",
  "was",
  "were",
  "can",
]);

/**
 * FRC jargon expansions. Each user token that hits a key becomes an OR-group.
 * Keep keys specific so "game" or "piece" do not explode the query.
 */
export const SYNONYMS: Record<string, string[]> = {
  intake: [
    "intake",
    "intakes",
    "indexer",
    "hopper",
    "overbumper",
    "underbumper",
    "roller",
    "rollers",
    "polycord",
    "polybelt",
    "pinch",
  ],
  indexer: ["indexer", "intake", "hopper", "serializer", "singulator"],
  hopper: ["hopper", "indexer", "magazine", "buffer"],
  shooter: ["shooter", "flywheel", "hood", "turret", "launcher", "outtake"],
  flywheel: ["flywheel", "shooter", "hood", "kicker"],
  elevator: ["elevator", "cascade", "continuous", "carriage", "stage", "lift"],
  cascade: ["cascade", "elevator", "stage"],
  arm: ["arm", "wrist", "pivot", "joint", "fourbar"],
  wrist: ["wrist", "pivot", "hinge"],
  climber: ["climber", "climb", "trap", "hang", "deepclimb"],
  gearbox: ["gearbox", "reduction", "gearing", "ratio", "planetary"],
  swerve: ["swerve", "module", "mk4", "mk4i", "mk4n", "mk5", "maxswerve", "thrifty", "sds"],
  mk4i: ["mk4i", "mk4", "mk4n", "sds", "swerve"],
  maxswerve: ["maxswerve", "rev", "swerve"],
  belt: ["belt", "htiming", "gt2", "httd", "polycord", "polybelt"],
  chain: ["chain", "25chain", "35chain", "sprocket"],
  pneumatics: ["pneumatic", "pneumatics", "cylinder", "solenoid", "air"],
  roller: ["roller", "rollers", "compliant", "colson", "stealth", "polycord"],
  compliant: ["compliant", "andymark", "durometer", "tread", "grippy"],
  wheel: ["wheel", "wheels", "compliant", "colson", "tread", "roller"],
  algae: ["algae", "algal", "processor", "reef", "coral", "reefscape"],
  algal: ["algae", "algal", "processor"],
  coral: ["coral", "algae", "reef", "trough", "reefscape"],
  note: ["note", "notes", "crescendo", "speaker", "amp", "underbumper"],
  notes: ["note", "notes", "crescendo", "speaker", "amp"],
  cone: ["cone", "cones", "cube", "charged"],
  cube: ["cube", "cubes", "cone", "charged"],
  cargo: ["cargo", "powercell", "cell", "ball"],
  hatch: ["hatch", "hatchpanel", "cargo"],
  ball: ["ball", "balls", "cargo", "fuel", "powercell", "boulder"],
  fuel: ["fuel", "ball", "highgoal", "shooter"],
  boulder: ["boulder", "ball", "intake"],
  tote: ["tote", "can", "recycle"],
  tube: ["tube", "inner", "outer"],
  frisbee: ["frisbee", "disc", "flyer"],
  disc: ["disc", "frisbee", "flyer"],
  ring: ["ring", "mogo", "mobilegoal"],
  polycord: ["polycord", "polybelt", "roundbelt", "intake"],
  overbumper: ["overbumper", "intake", "bumper"],
  underbumper: ["underbumper", "intake", "note", "ground"],
  reefscape: ["reefscape", "algae", "coral", "processor", "reef"],
  crescendo: ["crescendo", "note", "speaker", "amp", "trap"],
  charged: ["chargedup", "cone", "cube"],
  chargedup: ["chargedup", "cone", "cube"],
  "3dp": ["3dprint", "3dp", "3dprinted", "printed", "pla", "petg", "abs", "tpu", "filament"],
  "3dprint": ["3dprint", "3dp", "3dprinted", "printed", "pla", "petg", "abs", "tpu", "filament"],
  "3dprinted": ["3dprint", "3dp", "printed", "pla", "petg"],
  printed: ["3dprint", "3dp", "printed", "pla", "petg", "filament"],
  pla: ["pla", "petg", "abs", "tpu", "3dprint", "printed"],
  petg: ["petg", "pla", "abs", "3dprint", "printed"],
  camera: ["camera", "limelight", "photonvision", "arducam", "vision"],
  limelight: ["limelight", "camera", "photonvision", "vision"],
  photonvision: ["photonvision", "limelight", "camera", "vision"],
  vision: ["vision", "camera", "limelight", "photonvision", "apriltag"],
  mount: ["mount", "bracket", "housing", "shroud", "cage"],
  bracket: ["bracket", "mount", "housing"],
  robust: ["robust", "strength", "crack", "cracked", "broke", "broken", "fail", "failure", "stiff"],
  openalliance: ["openalliance", "oa"],
};

/** Tokens that match too much history if searched alone. */
export const WEAK_DISCOVERY_TOKENS = new Set([
  "camera",
  "cameras",
  "mount",
  "mounts",
  "robust",
  "vision",
  "printed",
  "printing",
  "bracket",
  "housing",
  "sensor",
  "sensors",
]);

const TOKEN_ALIASES: Record<string, string> = {
  "3dp": "3dprint",
  "3dprinted": "3dprint",
  "3dprinting": "3dprint",
  "3d-printed": "3dprint",
  "3d-print": "3dprint",
  mounts: "mount",
  cameras: "camera",
  robustness: "robust",
  limelights: "limelight",
  oa: "openalliance",
  "open-alliance": "openalliance",
};

export function normalizeToken(token: string): string {
  const key = token.toLowerCase().replace(/[^a-z0-9+.-]/g, "");
  return TOKEN_ALIASES[key] ?? key;
}

export const GAME_PIECES: Record<string, string> = {
  algae: "algae",
  algal: "algae",
  coral: "coral",
  note: "note",
  notes: "note",
  cone: "cone",
  cube: "cube",
  cargo: "cargo",
  hatch: "hatch",
  ball: "ball",
  fuel: "fuel",
  boulder: "boulder",
  tote: "tote",
  tube: "tube",
  frisbee: "frisbee",
  disc: "disc",
  ring: "ring",
  grommet: "ring",
  powercell: "cargo",
  "power cell": "cargo",
};

export function expansionsFor(token: string): string[] {
  const key = normalizeToken(token);
  const extra = SYNONYMS[key];
  const terms = extra ? [key, ...extra] : [key || token];
  return unique(terms.map((t) => t.toLowerCase()).filter((t) => t.length > 1));
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}
